Adapted for Sysnove.

diff --git a/common.sh.in b/common.sh.in
--- a/common.sh.in
+++ b/common.sh.in
@@ -19,41 +19,12 @@
 
 CLEANUP=( )
 
+declare -ri ONE_KIB=1024
+declare -ri ONE_MIB=$ONE_KIB*1024
+declare -ri ONE_GIB=$ONE_MIB*1024
+
 log_error() {
   echo "$@" >&2
-}
-
-get_api5_arguments() {
-  GETOPT_RESULT=$*
-  # Note the quotes around `$TEMP': they are essential!
-  eval set -- "$GETOPT_RESULT"
-  while true; do
-    case "$1" in
-      -i|-n) instance=$2; shift 2;;
-
-      -o) old_name=$2; shift 2;;
-
-      -b) blockdev=$2; shift 2;;
-
-      -s) swapdev=$2; shift 2;;
-
-      --) shift; break;;
-
-      *)  log_error "Internal error!" >&2; exit 1;;
-    esac
-  done
-  if [ -z "$instance" -o -z "$blockdev" ]; then
-    log_error "Missing OS API Argument (-i, -n, or -b)"
-    exit 1
-  fi
-  if [ "$SCRIPT_NAME" != "export" -a -z "$swapdev"  ]; then
-    log_error "Missing OS API Argument -s (swapdev)"
-    exit 1
-  fi
-  if [ "$SCRIPT_NAME" = "rename" -a -z "$old_name"  ]; then
-    log_error "Missing OS API Argument -o (old_name)"
-    exit 1
-  fi
 }
 
 get_api10_arguments() {
@@ -86,32 +57,104 @@ get_api10_arguments() {
   old_name=$OLD_INSTANCE_NAME
 }
 
+check_empty_sizes() {
+  # Check is there are more than 2 empty OSP_*_SIZE.
+  if [ -z "$OSP_ROOT_SIZE" -a -z "$OSP_SWAP_SIZE" ]; then
+    echo "Only one of root_size and swap_size can be empty."
+    exit 1
+  fi
+
+  if [ -z "$OSP_ROOT_SIZE" -a -z "$OSP_VAR_SIZE" ]; then
+    echo "Only one of root_size and var_size can be empty."
+    exit 1
+  fi
+
+  if [ -z "$OSP_SWAP_SIZE" -a -z "$OSP_VAR_SIZE" ]; then
+    echo "Only one of swap_size and var_size can be empty."
+    exit 1
+  fi
+}
+
+check_minimal_sizes() {
+  # Check minimal sizes
+  if [ -n "$OSP_ROOT_SIZE" -a "$OSP_ROOT_SIZE" -lt "$ROOT_MIN_SIZE" ]; then
+    echo "root FS size must be greater than ${ROOT_MIN_SIZE}MiB."
+    exit 1
+  fi
+
+  if [ -n "$OSP_SWAP_SIZE" -a "$OSP_SWAP_SIZE" -lt "$SWAP_MIN_SIZE" ]; then
+    echo "swap size must be greater than ${SWAP_MIN_SIZE}MiB."
+    exit 1
+  fi
+
+  if [ -n "$OSP_VAR_SIZE" -a "$OSP_VAR_SIZE" -lt "$VAR_MIN_SIZE" ]; then
+    echo "var FS size must be greater than ${VAR_MIN_SIZE}MiB."
+    exit 1
+  fi
+}
+
 format_disk0() {
-  # Create one big partition, and make it bootable
-  # some versions of sfdisk need manual specification of
-  # head/sectors for devices such as drbd which don't
-  # report geometry
-  sfdisk -H 64 -S 32 -u S --quiet --Linux "$1" <<EOF
-${PARTITION_ALIGNMENT},,L,*
+  blockdev="$1"
+
+  # PARTITION_ALIGNMENT is in sectors, converting it to bytes.
+  PA_BYTES=$((PARTITION_ALIGNMENT*512))
+
+  ROOT_START=$((PA_BYTES))
+  ROOT_END=$((ROOT_START+ROOT_SIZE*ONE_MIB-1))
+  SWAP_START=$((ROOT_START+1))
+  SWAP_END=$((SWAP_START+SWAP_SIZE*ONE_MIB-1))
+  VAR_START=$((SWAP_END+1))
+  VAR_END=$((VAR_START+VAR_SIZE*ONE_MIB-1))
+
+  $PARTED $blockdev <<EOF
+unit B
+mkpart primary $ROOT_START $ROOT_END
+set 1 boot on
+mkpart primary $SWAP_START $SWAP_END
+mkpart primary $VAR_START $VAR_END
 EOF
 }
 
 map_disk0() {
   blockdev="$1"
-  filesystem_dev_base=`kpartx -l -p- $blockdev | \
-                       grep -m 1 -- "-1.*$blockdev" | \
-                       awk '{print $1}'`
-  if [ -z "$filesystem_dev_base" ]; then
+
+  # Find device base names.
+  rootdev_base=`kpartx -l -p- $blockdev | \
+                grep -m 1 -- "-1.*$blockdev" | \
+                awk '{print $1}'`
+  swapdev_base=`kpartx -l -p- $blockdev | \
+                grep -m 1 -- "-2.*$blockdev" | \
+                awk '{print $1}'`
+  vardev_base=`kpartx -l -p- $blockdev | \
+               grep -m 1 -- "-3.*$blockdev" | \
+               awk '{print $1}'`
+
+  # Check *dev_base validity.
+  if [ -z "$rootdev_base" -o -z "$swapdev_base" -o -z "$vardev_base" ]; then
     log_error "Cannot interpret kpartx output and get partition mapping"
     exit 1
   fi
+
+  # Map devices.
   kpartx -a -s -p- $blockdev > /dev/null
-  filesystem_dev="/dev/mapper/$filesystem_dev_base"
-  if [ ! -b "$filesystem_dev" ]; then
-    log_error "Can't find kpartx mapped partition: $filesystem_dev"
-    exit 1
-  fi
-  echo "$filesystem_dev"
+
+  # Set device paths.
+  for dev in rootdev swapdev vardev; do
+    eval $dev="/dev/mapper/\$"$dev"_base"
+  done
+
+  # Check mapped devices.
+  for dev in $rootdev $swapdev $vardev; do
+    if [ ! -b "$dev" -o ]; then
+      log_error "Can't find kpartx mapped partition: $dev"
+      exit 1
+    fi
+  done
+
+  # Display evaluable variable assignation on stdout
+  for dev in rootdev swapdev vardev; do
+    eval echo $dev="\$$dev"
+  done
 }
 
 unmap_disk0() {
@@ -151,13 +194,15 @@ fi
 : ${GENERATE_CACHE:="yes"}
 : ${CLEAN_CACHE:="14"} # number of days to keep a cache file
 : ${PARTITION_ALIGNMENT:=2048} # sectors to align partition (1Mib default)
-if [ -z "$OS_API_VERSION" -o "$OS_API_VERSION" = "5" ]; then
-  DEFAULT_PARTITION_STYLE="none"
-else
-  DEFAULT_PARTITION_STYLE="msdos"
-fi
-: ${PARTITION_STYLE:=$DEFAULT_PARTITION_STYLE} # disk partition style
-: ${OSP_FILESYSTEM:="ext4"}
+: ${PARTITION_STYLE:="gpt"} # disk partition style
+: ${OSP_ROOT_FS:="ext4"}
+: ${OSP_ROOT_SIZE:="5120"} # 5GiB
+: ${OSP_SWAP_SIZE:="1024"} # 1GiB
+: ${OSP_VAR_FS:="ext4"}
+: ${OSP_VAR_SIZE:=""} # Rest of disk if empty
+: ${ROOT_MIN_SIZE:="5120"} # 5GiB
+: ${SWAP_MIN_SIZE:="1024"} # 1GiB
+: ${VAR_MIN_SIZE:="100"} # 100MiB
 
 CACHE_DIR="@localstatedir@/cache/ganeti-instance-debootstrap"
 
@@ -180,11 +225,15 @@ if [ -z "$VOL_ID" ]; then
   exit 1
 fi
 
+PARTED=$(which parted 2>/dev/null || true)
+if [ -z "$PARTED" ]; then
+  log_error "parted not found, please install it."
+  exit 1
+fi
+
 if [ -z "$OS_API_VERSION" -o "$OS_API_VERSION" = "5" ]; then
-  OS_API_VERSION=5
-  GETOPT_RESULT=`getopt -o o:n:i:b:s: -n '$0' -- "$@"`
-  if [ $? != 0 ] ; then log_error "Terminating..."; exit 1 ; fi
-  get_api5_arguments $GETOPT_RESULT
+  log_error "API v5 is not supported."
+  exit 1
 elif [ "$OS_API_VERSION" = "10" -o "$OS_API_VERSION" = "15" -o \
        "$OS_API_VERSION" = "20" ]; then
   get_api10_arguments
diff --git a/create b/create
--- a/create
+++ b/create
@@ -19,10 +19,6 @@
 
 set -e
 
-# minimum device size is 256 MB, but we use 255 to account for
-# potential rounding
-declare -ri MIN_DEV_SIZE=$((255*1048576))
-
 . common.sh
 
 if [ "$GENERATE_CACHE" = "yes" -a ! -d "$CACHE_DIR" ]; then
@@ -40,10 +36,31 @@ if [ ! -b $blockdev ]; then
   CLEANUP+=("losetup -d $blockdev")
 fi
 
+check_empty_sizes
+
+# Find device size.
 DEVICE_SIZE=$(blockdev --getsize64 $blockdev)
+
+# Compute the missing size.
+if [ -z "OSP_ROOT_SIZE" ]; then
+    OSP_ROOT_SIZE=$((DEVICE_SIZE/ONE_MIB-SWAP_SIZE-VAR_SIZE))
+elif [ -z "OSP_SWAP_SIZE" ]; then
+    OSP_SWAP_SIZE=$((DEVICE_SIZE/ONE_MIB-ROOT_SIZE-VAR_SIZE))
+elif [ -z "OSP_VAR_SIZE" ]; then
+    OSP_VAR_SIZE=$((DEVICE_SIZE/ONE_MIB-ROOT_SIZE-SWAP_SIZE))
+fi
+
+check_minimal_sizes
+
+# Check minimum disk size.
+
+# PARTITION_ALIGNMENT is in sectors, converting it to bytes.
+PA_BYTES=$((PARTITION_ALIGNMENT*512))
+declare -ri MIN_DEV_SIZE=$((PA_BYTES+(OSP_ROOT_FS+OSP_SWAP_SIZE+OSP_VAR_SIZE)*ONE_MIB))
+
 if [ "$DEVICE_SIZE" -lt $MIN_DEV_SIZE ]; then
-  echo "Device size is too small ($((DEVICE_SIZE/1048576)) MB)" 1>&2
-  echo "Required size is at least 256MB" 1>&2
+  echo "Device size is too small ($((DEVICE_SIZE/ONE_MIB))MiB)" 1>&2
+  echo "Required size is at least $((MIN_DEV_SIZE/ONE_MIB))MiB" 1>&2
   exit 1
 fi
 
@@ -52,26 +69,38 @@ if [ "$PARTITION_STYLE" = "none" ]; then
 elif [ "$PARTITION_STYLE" = "msdos" ]; then
   # Create one big partition, and make it bootable
   format_disk0 $blockdev
-  filesystem_dev=$(map_disk0 $blockdev)
+  eval $(map_disk0 $blockdev)
   CLEANUP+=("unmap_disk0 $blockdev")
+elif [ "$PARTITION_STYLE" = "gpt" ]; then
+    # Check if root_path is set to /dev/vda2 (or /dev/xvda2 for xen)
+    echo "gpt label is not supported yet."
+    exit 1
 else
   echo "Unknown partition style $PARTITION_STYLE" 1>&2
   exit 1
 fi
 
-mke2fs -Fjqt $OSP_FILESYSTEM $filesystem_dev
-root_uuid=$($VOL_ID $filesystem_dev )
+# Prepare failesystems
+mkfs.$OSP_ROOT_FS $rootdev
+root_uuid=$($VOL_ID $rootdev )
 
-if [ -n "$swapdev" ]; then
-  mkswap $swapdev
-  swap_uuid=$($VOL_ID $swapdev || true )
-fi
+mkswap $swapdev
+swap_uuid=$($VOL_ID $swapdev )
 
+mkfs.$OSP_VAR_FS $vardev
+var_uuid=$($VOL_ID $vardev )
+
+# Mount filesystems
 TMPDIR=`mktemp -d` || exit 1
 CLEANUP+=("rmdir $TMPDIR")
 
-mount $filesystem_dev $TMPDIR
+mount $rootdev $TMPDIR
 CLEANUP+=("umount $TMPDIR")
+
+mkdir $TMPDIR/var
+
+mount $vardev $TMPDIR/var
+CLEAN_CACHE+=("umount $TMPDIR/var")
 
 # remove the cache file if it's old (> 2 weeks) and writable by the owner (the
 # default due to the standard umask)
@@ -125,12 +154,10 @@ cat > $TMPDIR/etc/fstab <<EOF
 # /etc/fstab: static file system information.
 #
 # <file system>   <mount point>   <type>  <options>       <dump>  <pass>
-UUID=$root_uuid   /               $OSP_FILESYSTEM    defaults        0       1
-proc              /proc           proc    defaults        0       0
-EOF
-
-[ -n "$swapdev" -a -n "$swap_uuid" ] && cat >> $TMPDIR/etc/fstab <<EOF
+UUID=$root_uuid   /               $OSP_ROOT_FS    defaults        0       1
 UUID=$swap_uuid   swap            swap    defaults        0       0
+UUID=$var_uuid    /var            $OSP_VAR_FS    defaults        0       0
+proc              /proc           proc    defaults        0       0
 EOF
 
 cat > $TMPDIR/etc/network/interfaces <<EOF
diff --git a/verify b/verify
--- a/verify
+++ b/verify
@@ -19,14 +19,22 @@
 
 set -e
 
-case $OSP_FILESYSTEM in
-  ""|"ext2"|"ext3"|"ext4")
-    ;;
-  *)
-    echo "Invalid value '$OSP_FILESYSTEM' for the filesystem parameter" 1>&2
+. common.sh
+
+# Check if each OSP_*_FS is valid.
+if [ ! -x "/usr/bin/mkfs.$OSP_ROOT_FS" ]; then
+    echo "Invalid root_fs: the command /usr/bin/mkfs.$OSP_ROOT_FS does not exist."
     exit 1
-    ;;
-esac
+fi
+
+if [ ! -x "/usr/bin/mkfs.$OSP_VAR_FS" ]; then
+    echo "Invalid var_fs: the command /usr/bin/mkfs.$OSP_VAR_FS does not exist."
+    exit 1
+fi
+
+check_empty_sizes
+
+check_minimal_sizes
 
 exit 0
 
